const ACTIONS = {
    SET_COUNT: 'SET_COUNT',
    SET_COMPLITE: 'SET_COMPLITE',
    SET_DELETE: 'SET_DELETE',
    SET_TITLE: 'SET_TITLE',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
}

export default ACTIONS;