const ACTIONS = {
    ADD_TASK: 'ADD_TASK',
    DELETE_TASK: 'DELETE_TASK',
    SELECTED_TASK: 'SELECTED_TASK',
    EDIT_TASK: 'EDIT_TASK',
    SET_COMPLITE: 'SET_COMPLITE',
}

export default ACTIONS;